### ISSUE TITLE
Instance Storage not attached/available after "Start Instance"

### ISSUE THREAD

**Issue by ericzinnikas** [lg/cloudy-gamer#24]
As in the title, I've only got the EBS storage.  If I get some time I'll try to poke at the code and see what needs to be done to make sure the instance storage is attached.
 
![screen shot 2017-01-27 at 6 19 18 pm](https://cloud.githubusercontent.com/assets/3394214/22391125/558f9de8-e4bd-11e6-86e0-7de74a9b6207.png)

**Comment by ericzinnikas** [comment]
Seems like this is more of an issue with the base AMI, rather than the provisioning js.  I just duplicated the AMI and added in instance storage on /dev/xdc and it is now available.

![screen shot 2017-01-27 at 6 59 59 pm](https://cloud.githubusercontent.com/assets/3394214/22392025/3b0d877c-e4c3-11e6-845f-801f31e1ba3d.png)


The only thing missing is auto-formatting/mounting, looks like the EC2Config service was removed in the 2016 Server AMI: https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/windows-ami-version-history.html#win2k16-amis

**Comment by lg** [comment]
@ericzinnikas ah yeah, the EC2Config service was changed. there are some new ways of auto-initializing now with Windows Server 2016. if you're using these scripts, i'm curious, why do you find you need to attach another EBS volume? your Disk 1 there is kept alive between instances.

**Comment by ericzinnikas** [comment]
I wasn't attaching another EBS volume, Disk 2 is the instance store (I've been sticking games there since it is faster).  Though I could just try keeping everything on Disk 1, I haven't really tested the performance difference yet (still troubleshooting shoddy Steam In-Home performance).

**Comment by lg** [comment]
yeah once you warm the drive (use the link thats created on the desktop), the EBS volume is *fast*

**Comment by ericzinnikas** [comment]
Yeah, looks like EBS is good enough (90MB/s vs 900MB/s doesn't make much of a difference :) ).

**Comment by lg** [comment]
excellent, happy gaming!
