### ISSUE TITLE
Handle VPC-only EC2 accounts

### ISSUE THREAD

**Issue by ericzinnikas** [lg/cloudy-gamer#25]
I've noticed whenever I try to start an instance, I see:
```
2017-01-28 17:46:49.401   Creating non-VPC Security Group...
https://ec2.us-east-1.amazonaws.com/ Failed to load resource: the server responded with a status of 400 (Bad Request)
aws-sdk.min.js:38 Uncaught (in promise) Error: The security group 'cloudygamer' already exists for VPC 'vpc-42de0027'
    at constructor.extractError (aws-sdk.min.js:38)
    at constructor.callListeners (aws-sdk.min.js:38)
    at constructor.emit (aws-sdk.min.js:38)
    at constructor.emitEvent (aws-sdk.min.js:37)
    at constructor.e (aws-sdk.min.js:37)
    at a.runTo (aws-sdk.min.js:39)
    at aws-sdk.min.js:39
    at constructor.<anonymous> (aws-sdk.min.js:37)
    at constructor.<anonymous> (aws-sdk.min.js:37)
    at constructor.callListeners (aws-sdk.min.js:38)
```

Deleting the security group for that VPC id then re-running start instance works.  The first log line is: "Creating non-VPC Security Group...", but this method seems to in fact create a VPC Security Group.

But it seems like the larger issue is actually (from AWS docs):

> If you created your AWS account after 2013-12-04, it supports only EC2-VPC

So many accounts (like mine) will not be able to create non-VPC security groups, thus the check [here](https://github.com/lg/cloudy-gamer/blob/45e07091d57cf6f127579d3e4982252afd6dc5e0/cloudy-gamer.js#L156-L159) won't work.  The solution is probably to do [this](https://github.com/lg/cloudy-gamer/blob/45e07091d57cf6f127579d3e4982252afd6dc5e0/cloudy-gamer.js#L221) check differently, adding a check if someone's account is VPC only (or in an earlier step).  Looks like the [DescribeAccountAttributes](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeAccountAttributes.html) method is what we want.  If I get time later today I'll submit a PR.

**Comment by lg** [comment]
wow, that would explain the lower Spot prices for non-VPC. thanks for looking into this. PRs are welcome!

probably do that `DescribeAccountAttributes` call and if EC2-Classic isn't supported, do not attempt to create the non-VPC security group (or even check for it). you might need to also add something to not get the EC2-Classic Spot prices (or attempt to launch a EC2-Classic instance). oh and the `user-policy.txt` file will need updating too. man, we should probably just recommend all permissions instead of all these one-offs...

**Comment by lg** [comment]
fixed by https://github.com/lg/cloudy-gamer/commit/ec7f7712b5aa8ad527c74a05072aa0b25a52a366. can you verify?

**Comment by lg** [comment]
assuming fixed. closing, let me know if this is still an issue.
