### ISSUE TITLE
Missing Z:

### ISSUE THREAD

**Issue by xProteus** [lg/cloudy-gamer#27]
Hiya,
I've taken the jump from using the premade community ami to trying out the provisioning script in the repo. It works very well automagically, but it looks like it doesn't set the Z: mount.

It seems some config needs to be changed from the base Win 2016 image, and found this documented in the "Initialize Drives and Drive Letter Mappings" section of http://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2launch.html

I've opened https://github.com/lg/cloudy-gamer/pull/26 if anyone is interested.

**Comment by lg** [comment]
fixed by https://github.com/lg/cloudy-gamer/pull/26. thanks for the contribution!
