### ISSUE TITLE
cloudygamer-loader5 ami not available in EU

### ISSUE THREAD

**Issue by bcoddens** [lg/cloudy-gamer#28]
Dear,

I cannot find the ami in the EU regions.  I mosty use London, Ireland or Frankfurt

Best Regards,
Bart

**Comment by lg** [comment]
it should be there. in Ireland its `ami-87f6daf4`, in Frankfurt its `ami-febb7991` and in London they don't have GPU instances rolled out there yet.

good luck!

**Comment by bcoddens** [comment]
Thanks for the quick reply, I cannot find it in Frankfurt, is the ami public ?
Filtering on ami-id and on the name: cloudygamer-loader5 does not give me results

**Comment by lg** [comment]
oh you're right. apologies for that. not sure how all of them became private. they're all public now!
