### ISSUE TITLE
Cloudygamer.psm1: powershell could not create ssl/tsl secure

### ISSUE THREAD

**Issue by 3urningChrome** [lg/cloudy-gamer#32]
Cloudygamer.psm1 script fails on getting zerotier vpn due to:
Exception calling "DownloadFile" with "2" argument(s): "The request was aborted: Could not create SSL/TLS

solution - Add this line before the download: 
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

(May also need to do this before the 7zip download, I can't remember now)

NOTE: I don't really understand any of this, but after adding the above line, the script worked from start to finish

**Comment by lg** [comment]
added the line, though not sure why .net isn't forcing the latest TLS to begin with. let me know if you discover more issues and i'll dig into it. thanks for reporting.
