### ISSUE TITLE
AMIs in eu-*

### ISSUE THREAD

**Issue by passy** [lg/cloudy-gamer#4]
Hey,

I'm a total AWS noob. This is literally the reason why I've signed up. I've tried to copy `cloudygamer-loader5` from `us-west-1` to `eu-west-2` but I'm getting the error "You do not have permission to access the storage of this ami". Is that something you can fix?

Thanks and happy new year.

**Comment by lg** [comment]
hrm, forgot to also set the Snapshot permissions. try it now. i'll also make some copies since i don't intend on changing the loader any time soon

**Comment by lg** [comment]
cool, i started copies to all regions with g2.2xlarge instances, should be done shortly. happy new year!

**Comment by ericzinnikas** [comment]
FWIW there weren't any in us-east-1, so I copied it there too (public).

**Comment by lg** [comment]
@ericzinnikas i took a quick look, `ami-f57d63e2` should be the AMI there?

**Comment by ericzinnikas** [comment]
This is the only thing that comes up when I search by name (my AMI), searching with that ID shows 0 results.  Is it set to public?

![screen shot 2017-01-27 at 10 04 19 pm](https://cloud.githubusercontent.com/assets/3394214/22393799/983f18b6-e4dc-11e6-8313-9fd6158bca4b.png)
